dataset:
  use_hf: true
  hf_datasets:
    - name: "theekshana/sinhala-news-sentiment-classification"
      split: "train"
      alias: "sinhala"
      text_field: "text"
      label_field: "label"
    - name: "carant-ai/english_sentiment_dataset"
      split: "train"
      alias: "english"
      text_field: "content"
      label_field: "sentiment"
  output_dir: "data/processed"
  seed: 42
